apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - cnpg-operator.yaml
  - argo-workflows/
  - argocd/
  - kargo/
  - infisical/
  - caddy/
  - authelia/
  - ddns/
  - alloy/