apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: game-servers
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/component: minecraft
    app.kubernetes.io/managed-by: argocd
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: minecraft
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
