api:
  enabled: true
  host: kargo.saavylab.dev
  adminAccount:
    enabled: true
  secret:
    name: kargo-api-secret
  tls:
    enabled: false
    terminatedUpstream: true
  rollouts:
    integrationEnabled: false

externalWebhooksServer:
  enabled: false

webhooks:
  register: false

webhooksServer:
  enabled: false

controller:
  argocd:
    integrationEnabled: true
    namespace: argocd
  rollouts:
    integrationEnabled: false
