apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - project.yaml
  - project-config.yaml
  - secret-store.yaml
  - external-secrets.yaml
  - warehouse.yaml
  - stage-prod.yaml
