controllers:
  ddns:
    type: deployment
    containers:
      main:
        image:
          repository: favonia/cloudflare-ddns
          tag: latest
          pullPolicy: Always
        env:
          DOMAINS: saavylab.dev,mc.saavylab.dev,auth.saavylab.dev,nexus.saavylab.dev,workflows.saavylab.dev,argocd.saavylab.dev,kargo.saavylab.dev,infisical.saavylab.dev,registry.saavylab.dev,watch.saavylab.dev,shows.saavylab.dev,movies.saavylab.dev,downloads.saavylab.dev,fbi.saavylab.dev,indexers.saavylab.dev,subtitles.saavylab.dev,grafana.saavylab.dev
          PROXIED: "true"
        envFrom:
          - secretRef:
              name: ddns-env
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
